from django.urls import path
from . import views


urlpatterns = [
    path("events/", views.EventListView.as_view()),
    path("events/<int:pk>/", views.EventDetailView.as_view()),
    path("events/create", views.EventCreateView.as_view()),
    path("events/update/<int:pk>", views.EventUpdateView.as_view()),
    path("events/delete/<int:pk>", views.EventDeleteView.as_view()),
    path("performers/", views.PerformerListView.as_view()),
    path("performers/<int:pk>/", views.PerformerDetailView.as_view()),
    path("performers/create", views.PerformerCreateView.as_view()),
    path("performers/update/<int:pk>", views.PerformerUpdateView.as_view()),
    path("performers/delete/<int:pk>", views.PerformerDeleteView.as_view()),
    path("agecategories/", views.AgeCategoryListView.as_view()),
    path("agecategories/<int:pk>/", views.AgeCategoryDetailView.as_view()),
    path("agecategories/create", views.AgeCategoryCreateView.as_view()),
    path("agecategories/update/<int:pk>", views.AgeCategoryUpdateView.as_view()),
    path("agecategories/delete/<int:pk>", views.AgeCategoryDeleteView.as_view()),
    path("cities/", views.CityListView.as_view()),
    path("cities/<int:pk>/", views.CityDetailView.as_view()),
    path("cities/create", views.CityCreateView.as_view()),
    path("cities/update/<int:pk>", views.CityUpdateView.as_view()),
    path("cities/delete/<int:pk>", views.CityDeleteView.as_view()),
    path("placetypes/", views.PlaceTypeListView.as_view()),
    path("placetypes/<int:pk>/", views.PlaceTypeDetailView.as_view()),
    path("placetypes/create", views.PlaceTypeCreateView.as_view()),
    path("placetypes/update/<int:pk>", views.PlaceTypeUpdateView.as_view()),
    path("placetypes/delete/<int:pk>", views.PlaceTypeDeleteView.as_view()),
    path("places/", views.PlaceListView.as_view()),
    path("places/<int:pk>/", views.PlaceDetailView.as_view()),
    path("places/create", views.PlaceCreateView.as_view()),
    path("places/update/<int:pk>", views.PlaceUpdateView.as_view()),
    path("places/delete/<int:pk>", views.PlaceDeleteView.as_view()),
    path("genres/", views.GenreListView.as_view()),
    path("genres/<int:pk>/", views.GenreDetailView.as_view()),
    path("genres/create", views.GenreCreateView.as_view()),
    path("genres/update/<int:pk>", views.GenreUpdateView.as_view()),
    path("genres/delete/<int:pk>", views.GenreDeleteView.as_view()),
    path("performertypes/", views.PerformerTypeListView.as_view()),
    path("performertypes/<int:pk>/", views.PerformerTypeDetailView.as_view()),
    path("performertypes/create", views.PerformerTypeCreateView.as_view()),
    path("performertypes/update/<int:pk>", views.PerformerTypeUpdateView.as_view()),
    path("performertypes/delete/<int:pk>", views.PerformerTypeDeleteView.as_view()),
    path("eventtypes/", views.EventTypeListView.as_view()),
    path("eventtypes/<int:pk>/", views.EventTypeDetailView.as_view()),
    path("eventtypes/create", views.EventTypeCreateView.as_view()),
    path("eventtypes/update/<int:pk>", views.EventTypeUpdateView.as_view()),
    path("eventtypes/delete/<int:pk>", views.EventTypeDeleteView.as_view())
]

